### ISSUE TITLE
Is it possible to create custom property for element?

### ISSUE THREAD

**Issue by mastermarkus** [Roblox/roact#12]
Hello i ran into issue, i was trying to make Material Design like button with extra functionality and ripple effect and i had to create custom property that could be specified just like Roblox  properties, but it threw error and told me it's not valid Property of rblxGui Element. 

QUESTION: Why not accept all Property names that are specified in properties table, why not let mix roblox properties and custom specified properties?

How would i go about making custom property for Button that has more functionality and features than original roblox button?

I already made two components ButtonComponent and RippleEffectComponent but im stuck at trying to figure out how to go about custom properties.

Also it would be nice if the documentation was fixed :), right now it leads to error page.

**Comment by LPGhatguy** [comment]
It doesn't make sense to pass custom properties to Roblox objects, because Roblox objects can't possibly do anything with them. Roblox throws an error when trying to set invalid properties because they're indistinguishable from typos!

You can accept whatever properties you want from your custom components though, just make sure to make a version of the `props` table that doesn't have those values before you give it to a Roblox object.

For example:

```lua
local RippleButton = Roact.Component:extend("RippleButton")

-- RippleButton accepts any props that TextButton does!
-- It also accepts some custom props for configuring its effects, which we have
-- to strip out before we pass them to TextButton.
local customProps = {
	-- I made up all these property names for this example
	rippleDuration = true,
	rippleType = true,
	materialHeight = true,
}

function RippleButton:render()
	-- Make a version of `self.props` without our custom properties
	-- Here, we can also assign some defaults!
	local childProps = {
		Size = UDim2.new(0, 200, 0, 50),
		BackgroundColor3 = Color3.new(0, 0, 0),
		BorderSizePixel = 0,
	}

	for key, value in pairs(self.props) do
		if not customProps[key] then
			childProps[key] = value
		end
	end

	return Roact.createElement("TextButton", childProps)
end
```
