### ISSUE TITLE
Merge stateful component and mount instances

### ISSUE THREAD

**Issue by TylerRHoyer** [Roblox/roact#130]
Right now stateful components keep a reference to the mounted instance in the reconciler called "handle." Because both have the same lifetime and both codebases touch the same information (the Component module is deeply involved in the reconciliation process for stateful components), I recommend we merge them. This prevents an additional table from being created for every stateful element and prevents some overhead for the reference. If in the future #125 is implemented, this change becomes even more natural because all the stateful element reconciliation is done inside of the Component module.

As a side note, the division of reconciliation duties feels fuzzy to me between the Reconciler and Component source code. I'd look into it more, but the problem has already been fixed in my version due to the changes suggested in #125.

**Comment by AmaranthineCodices** [comment]
This used to actually be the case, but @LPGhatguy mentioned once that it was removed to prevent access to `setState` and other component methods from outside the component instance itself, e.g.

```lua
local handle = mount(element)
-- evil: setState is supposed to be internal
handle:setState({
    -- ...
})
```

**Comment by LPGhatguy** [comment]
(@AmaranthineCodices beat me to responding, but I'll still have this write-up)

This was actually intentional! It tries to serve two purposes:

1. Limit the number of extra values put into the component instance, since that namespace belongs to the creator of the component, not Roact.
2. Stop users of Roact from calling component methods on the object returned by `Roact.mount`/`Roact.reify`. There's another approach for this, and that would be to make a special object _only_ for the direct result of `mount`.
