### ISSUE TITLE
Rename `Roact.Change` to `Roact.Changed`?

### ISSUE THREAD

**Issue by LPGhatguy** [Roblox/roact#151]
It's possible that `Changed` is a better name than `Change` for Roact's declarative version of `GetPropertyChangedSignal`.

I don't think we talked about this when the API was introduced, but `Changed` would line up better with Roblox conventions where events are described in the past tense.

**Comment by tiffany352** [comment]
I'm not happy about the API churn, but I do type `Changed` a lot mistakenly when writing out handlers in Roact code.

**Comment by LPGhatguy** [comment]
Right, this is a fairly minor change. We could keep both, or at least have a migration window. I wouldn't be too fond of having two different ways to express the same thing in the long term, though.

**Comment by Fraktality** [comment]
There's no ambiguity when you're writing Changed: The property has already changed; reading it will give you the new value.
Change could mean that the property has already updated, or maybe not, or maybe reading it is a race condition. Who knows.

> Changed would line up better with Roblox conventions where events are described in the past tense.

There's no convention; the Roblox API just uses whatever tense is correct.
`ChildRemoved` is past tense because the child has already been removed.
`PlayerRemoving` is present tense because we haven't removed the player yet.

**Comment by ZoteTheMighty** [comment]
I agree with most of what's said here, but I think it's worth noting that newer APIs seem to be favoring past tense.

Present progressive (-ing) is more of a special case than an example of present vs. past, since for a lot of APIs you have the choice of using the regular present tense (e.g. "Click") vs the past tense ("Clicked").

**Comment by tiffany352** [comment]
I don't know about that - Click vs Clicked feels more like PlayerRemove vs PlayerRemoved. The PlayerRemoving equivalent for Click would be "Clicking" I guess. I don't know how to describe this difference though...

**Comment by AmaranthineCodices** [comment]
note: "click" also serves as a noun, while "remove" does not - that may be the difference between the two? English is *weird*.

I'm not super sure why I picked `Change` instead of `Changed` - it may have been mimicking how `Roact.Event` uses `Event` as a noun. `Changed` is probably a better name for it regardless, because of how it lines up with GetProperty*Changed*Signal and Instance.*Changed*.

The API churn is kind of messy, but we can mitigate it in the same way that we did `reify` and `teardown`.

**Comment by ZoteTheMighty** [comment]
Right, "click" was a bad example.  New input APIs like "InputBegan" are closer to what I was trying to point out, where we could have chosen "InputBegin" and lined up the tense with old ones like "MouseEnter", but instead we skewed towards past tense.

**Comment by LPGhatguy** [comment]
I think the time for this issue has passed with the release of 1.0.
