### ISSUE TITLE
Give useful error messages when calling `setState` in the wrong places

### ISSUE THREAD

**Issue by LPGhatguy** [Roblox/roact#17]
Right now, there are three places where calling `setState` is a really bad idea:
* Inside `init` (the component is not initialized and throws an unrelated error)
* Inside `render` (render needs to be pure)
* After the component is unmounted (aah!)

We should keep track of some sort of state on each component and make sure these `setState` errors are surfaced well.

**Comment by AmaranthineCodices** [comment]
This should be fairly easy unless I'm missing something:

* Store a flag in the component instance: `_canSetState` or something. Defaults to false.
* Once the component is initialized, set the flag to true.
* Immediately before the component's `render` method is called, set the flag to false.
* Immediately after `render` finishes invocation, set the flag to true again.
* When the component is unmounted, set the flag to false.
* When `setState` is called, if `_canSetState` is false, throw an error. Otherwise, set the state and dispatch renders.

Does this look like a good approach? I can make a PR for this if so.

**Comment by LPGhatguy** [comment]
That sounds good to me!
