### ISSUE TITLE
Feature request: Freeze the reconciler on Visible false elements, or through some other API

### ISSUE THREAD

**Issue by headjoe3** [Roblox/roact#177]
I am planning on using Roact for a large-scale project—however, since my UI contains potentially hundreds of elements that are rapidly switched through menus, I usually just cache menus and set their "Visible" property to false while they are not visible.

The problem with this is that objects are still created, destroyed, or modified within trees that are invisible to the user, which almost defeats the purpose of this caching.

It seems reasonable to me that the reconciler should freeze on GuiObject descendants whenever a GuiObject with a "Visible" property of false is encountered—so that they are not created, modified, or destroyed redundantly.

If this is not feasible, it would be very helpful if there were some API to freeze the reconciler on a given element, so that all currently-rendered Instances remain untouched while the reconciler is frozen.

**Comment by LPGhatguy** [comment]
Thanks for filing an issue!

The easiest way to do this is to implement [`shouldUpdate`](https://roblox.github.io/roact/api-reference/#shouldupdate) for your components that you want to skip updates for. You can then ignore updates if `Visible` is false and resume them once it flips back to true!

We've talked about features like this before and in general, it's too specific to land in Roact itself, especially because it has a straightforward user-land solution via `shouldUpdate`.

**Comment by LPGhatguy** [comment]
You probably shouldn't ship a library abusing Roact internals like this, they're bound to break! You'll definitely make consumers of your library upset when everything blows up!

In fact, the moment we merge the `new-reconciler` branch, any of your current `applyMod` stuff will stop working, and there won't be a way to make code that works both with and without those changes.

**Comment by headjoe3** [comment]
Got it. I'll change the implementation.

I thought that `shouldUpdate` wouldn't cut it, because I was detecting component updates, but it turns out all of that is coming from Rodux, not Roact. I'll probably make some API that interfaces with rodux better.
