### ISSUE TITLE
Rendering does not update TextBox.Text if it is in a wrapper component reading prop value

### ISSUE THREAD

**Issue by zaiisao** [Roblox/roact#238]
https://www.roblox.com/games/3942160614/Roact-text-box-strange-behavior

In this place, I use a text box wrapper component where the text of the text box is stored in the state of the page component and the text box wrapper component filters text. The value of the state property (denoted as "value:"), the text in the TextBox (denoted as "rbx.Text"), and the expected text (denoted as "result:") are all printed in the output. When Roact renders the page component upon update of state, the text box seems to not change.

**Comment by MisterUncloaked** [comment]
@LPGhatguy , @zaiisao and I spoke today, and we decided this won't end up being a fix in Roact. Since the `Text` on the instance can change outside of Roact's knowledge (i.e. when the user is typing), it makes more sense to directly change the text using a ref in `componentDidUpdate` when implementing features like filtered text, to make sure the instance's `Text` is always correct.
