### ISSUE TITLE
Is there a Roact version of React's key prop?

### ISSUE THREAD

**Issue by blake-mealey** [Roblox/roact#292]
I have been looking in the docs for something analogous to React's `key` prop (identifies an element in an array so that it is not reused for a different element if the array changes) but have not found anything. At the moment, if my array changes I am setting it to empty, rendering, then setting it to the new array and rendering again to avoid the new elements maintaining state from the old elements. It would be great if there was a way to provide a unique key for each array element to fix this.

The API could look like this:

```lua
Roact.createElement(MyComponent, {
    [Roact.Key] = "my-key"
})
```

**Comment by ZoteTheMighty** [comment]
Hi! I think there's a few things to address here.

## Keys
The current version of Roact uses the keys provided in children tables as essentially the same thing. In Roblox, the order of an array of children isn't meaningful; instead, we need to use `LayoutOrder` or absolute positioning to order siblings correctly.

Because of this necessity, the ordering in something like this has no meaning:
```
Roact.createElement("Frame", nil, {
   Roact.createElement("TextLabel", { ... }),
   Roact.createElement("TextBox", { ... }),
})
```

Instead, we encourage users to specify children as a map, where the keys of the map are the stable keys you want to associate with each child:
```
Roact.createElement("Frame", nil, {
   Label = Roact.createElement("TextLabel", { ... }),
   Input = Roact.createElement("TextBox", { ... }),
})
```

There's some references to this behavior in the docs here: https://roblox.github.io/roact/performance/reduce-reconciliation/#stable-keys

I should note that future versions of Roact may take a different approach here! But for now, you can specify keys via the keys in your child tables, or via named keys in fragments.

## Picking up Old State
It seems like part of the problem you're having here: "...to avoid the new elements maintaining state from the old elements" has to do with your elements not specifying the right props to be fully updated. The purpose of using stable keys is to minimize effort; not to carry over some implicit state.

If you're talking about Instance properties (e.g. I need to re-render so that some default value is restored), you probably just want to specify that prop explicitly. If you're talking about actual state of your elements, and you need it to be updated when your elements reorder, you may consider hoisting some of that information up to the parent, which would then be able to tell each element what state it's rendering with.

**Comment by blake-mealey** [comment]
Thank you, I looked everywhere in the docs except the performance section haha. This will solve my problem :)
