### ISSUE TITLE
New mechanism for global configuration

### ISSUE THREAD

**Issue by LPGhatguy** [Roblox/roact#40]
I've thought a lot about #25 and related issues, and I think that there might be a need for an application-level global configuration that's set once and immutable.

Particularly, I'd like to have settings like:

* Trace all Roblox mutations (#27)
* Enable traceback storage on element creation (currently `DEBUG_ENABLE`)
* Set the frame budget for async rendering
* Automatically deep-freeze props and state for debugging

The API I'd be looking for would be something like:

```lua
Roact.setGlobalConfig({
    elementTracing = true,
    deepFreezePropsAndState = true
})
```

Any calls to `setGlobalConfig` after the first would throw an error.

**Comment by AmaranthineCodices** [comment]
This would be awesome. Should it have specific allowed values (so trying to set a non-legal value throws), or should it allow arbitrary keys (for external libraries to hook into)?

Since this is for a global configuration that is set once, and only once, it can probably be made hard-immutable by (deep?)cloning the input table and throwing on any mutation (via a proxy table).
